### PR TITLE
Fetch dvm git data with --all option

### LINKED ISSUE #68: Upgrade from 0.9.x to 0.10.x failure
**Describe the bug**
```
╭─fraggle at nemesis in ~
╰─○ dvm upgrade
HEAD est maintenant à 6dae8a3 v0.9.1
erreur : le spécificateur de chemin 'v0.10.0' ne correspond à aucun fichier connu de git
DVM has upgrade to latest version, please restart your terminal or run `source /home/fraggle/.zshrc` to apply changes.
```

The latest tags 0.10 is not pulled from the origin branch.

In `~/.dvm`, running `git pull origin --tags` fix the `dvm upgrade` error. 

**To Reproduce**
Run dvm upgrade from a dvm installation < 0.10.

### PR DESCRIPTION
**Pull request by ghosind**
Fetch DVM Git data with the `--all` option to ensure that tags are pulled.

Fix #68 .

### CODE REVIEW

File: dvm.sh [hunk 1]
```diff
@@ -1974,13 +1974,15 @@ export DVM_VERSION="v0.10.0"
     fi
 
     # reset changes if exists
-    git reset --hard HEAD
-    git fetch
-    git checkout "$DVM_LATEST_VERSION"
-
-    dvm_print "DVM has upgrade to latest version, please restart your terminal or run \`source $DVM_PROFILE_FILE\` to apply changes."
+    if git reset --hard HEAD && git fetch --all && git pull origin master --tag && git checkout "$DVM_LATEST_VERSION"
```
Comment (jerome-benoit) [inline dvm.sh:1977]: Not sure the `fetch --all` is necessary

Comment (ghosind) [reply dvm.sh:1977]: `fetch --all` should be enough for this problem, and I keep `pull --tags` to double check

Comment (jerome-benoit) [reply dvm.sh]: The branch to fetch is not in a global variable?

Comment (ghosind) [reply dvm.sh]: No, it is in the global variable `DVM_LATEST_VERSION`
